package com.app.focustimer.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a timer session record in the "timer_session" database table.
 */
@Entity(tableName = "timer_session")
data class TimerSessionEntity(
    /**
     * Unique ID for the session (auto-generated by Room). Primary key.
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id") val id: Int = 0,

    /**
     * Date of the timer session (format determined by app logic).
     */
    @ColumnInfo(name = "date") var date: String,

    /**
     * Value associated with the session (e.g., duration in milliseconds).
     */
    @ColumnInfo(name = "value") var value: Long
)